### ISSUE TITLE
App crashes when opening repository selection

### ISSUE THREAD

**Issue by funkenstrahlen** [cocreation/gitshot#13]
One of my repositories I have worked on with GitShot got removed from Github. When I open the app now it tries to load the repository issues but never finishes (because the repository is gone).

When I try to open the repository selection view on the top left to switch to another repository the app crashes immediately.

I tried to reinstall the app but this did not help unfortunately.

You can see the crashlog here: https://gist.github.com/11387a3c315af6ef1b7ae4f8baa07874

**Comment by jeanfw** [comment]
Hi @funkenstrahlen, thanks for the detailed report and sorry for the bad experience. 

This seems to be a crash in AlamoFireImage (while loading organization images). I had something similar myself on a dev build (although not with a repository removed from GitHub) and fixed it by updating to the latest AlamoFire version, so hopefully, your crash will be fixed in the next version too.

Could you let me know if it is indeed solved once you have v1.3.0? Thanks!

**Comment by funkenstrahlen** [comment]
Thank you for taking your time and working on the issue!

I will let you know if the update fixes the issue.

**Comment by jeanfw** [comment]
`v1.3.0` is now [available on the App Store](https://itunes.apple.com/us/app/gitshot/id1344912689?ls=1&mt=8&ct=github) -- please feel free to close if OK, or let me know if it still crashes. Hoping this was it ! 🤞

**Comment by funkenstrahlen** [comment]
The update fixes the issue. Thanks for your great work! 🙂
